POST /api/Students HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "name":"John",
    "course":"DATA2410",
    "marks":23
}

POST /api/Students HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "name":"Alice",
    "course":"PROG2053",
    "marks":87
}

POST /api/Students HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "name":"Bob",
    "course":"DATA2410",
    "marks":45
}

POST /api/Students HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "name":"Eve",
    "course":"MATH1001",
    "marks":92
}

POST /api/Students HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "name":"Charlie",
    "course":"DCSG1005",
    "marks":68
}

DELETE /api/Students/2 HTTP/1.1
Host: localhost:3000

PUT /api/Students/1 HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "name":"John Smith",
    "course":"DATA2410",
    "marks":78
}

POST /api/Students/calculate-grades HTTP/1.1
Host: localhost:3000

### Hent kursvis rapport
GET http://localhost:3000/api/Students/report